name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@f1615b835d3a5a2a4f7e276066336e0d3c04a0e1 # Pinned to v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}